language: java

jdk:
  - openjdk6
  - oraclejdk7
  - oraclejdk8

sudo: false

before_install:
    - cp src/build/travis-toolchains.xml ~/.m2/toolchains.xml

install: mvn -DskipTests=true -Dbasepom.check.skip-all=true -Dbasepom.it.skip=true -B install
script: mvn -B verify

